name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMG_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ${{ env.IMG_NAME }}:${{ steps.metadata.outputs.tags }}
        docker run ghcr.io/zahlenhelfer/zh-custom-nginx:${{ steps.metadata.outputs.tags }}
        docker push ghcr.io/zahlenhelfer/zh-custom-nginx:${{ steps.metadata.outputs.tags }}
